#!/bin/bash

userid=$(id -u)
if [ $userid -eq 0 ]
then
    echo "you are running with the root access"
else
    echo "ERROR: please run with the roor acces"
fi

dnf install nginx
if [ $? -eq 0 ]
    echo "nginx is installed and success"
    
else
    ech "nginx need to install"
fi